config/routes.rb
Rails.application.routes.draw do

  get 'tasks' => 'tasks#index'

  get 'tasks/new' => 'tasks#new', as: :new_task
  post 'tasks' => 'tasks#create'

  get 'tasks/:id' => 'tasks#show', as: :task

  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id/destroy', to: 'tasks#destroy', as: :delete_task

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    # Create the object with the inputs from the form
    @task = Task.new
  end

  def create
    # Give persistence to the object, store it in the DB
    #
    # @task = Task.new(name: params[:name], date:....)
    # @task = Task.new(params[:task])

    @task = Task.new(task_params)
    @task.save
    # This is the rails way

    #redirect to url: /tasks/:id
    redirect_to task_path(id: @task.id)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])

    @task.update(task_params)

    redirect_to task_path(id: @task.id)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    # It's private to access this variables
    params.require(:task).permit(:name, :date, :check)

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTaskManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>

<!-- List -->

<%= link_to 'New Task', new_task_path %>
<h1>Nr of tasks: <%= Task.count %></h1>

<% @tasks.each do |t| %>
  <h2><%= t.name %></h2>
  <p>Date: <%= t.date %></p>
  <p>Done? <%= t.check %></p>
  <%= link_to 'Show', task_path(id: t.id) %>
  <%= link_to 'Delete', delete_task_path(id: t.id), method: :delete %>
<% end %>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<p>Find me in app/views/tasks/new.html.erb</p>

<!-- New -->
<!-- It stores the inputs in an object task -->
<%= form_for @task do |t| %>
  <%= t.text_field :name, placeholder: 'Name' %>
  <%= t.datetime_local_field :date, placeholder: 'date' %>
  <%= t.check_box(:check) %>
  <%= t.submit %>
<% end %>

<!-- It will store the input values in the form: task{ name: ..., date: ..., check: ... } -->

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>

<!-- Shows individual tasks -->
<!-- it's rendered by the controller on the show action -->
<h1>Task - <%= @task.name %></h1>
<p>Date -> <%= @task.date %></p>
<p>Done? -> <%= @task.check %></p>

<%= link_to 'List All', tasks_path %>
<%= link_to 'Delete', delete_task_path(id: @task.id), method: :delete %>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>